// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservaFacil.Api.Data;
using ReservaFacil.Api.Models;

#nullable disable

namespace ReservaFacil.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905010642_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "EstadoCaja", new[] { "abierta", "cerrada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "EstadoPago", new[] { "pendiente", "pagado", "parcial", "reembolsado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "EstadoReserva", new[] { "pendiente", "confirmada", "cancelada", "completada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "EstadoTorneo", new[] { "borrador", "inscripciones_abiertas", "en_curso", "finalizado", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "MetodoPago", new[] { "efectivo", "yape", "culqi", "tarjeta", "transferencia" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "Rol", new[] { "usuario", "personal", "admin", "superadmin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "TipoCancha", new[] { "futbol", "futbol5", "futbol7", "padel", "tenis", "basquet", "volleyball", "loza" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "TipoDescuento", new[] { "porcentaje", "monto_fijo", "precio_especial" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "TipoMeta", new[] { "ingresos", "ocupacion", "reservas" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "TipoMovimiento", new[] { "reserva", "snack", "alquiler", "abono", "egreso", "ajuste" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservaFacil.Api.Models.CajaSesion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbiertaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("abiertaEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("AbiertaPorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abiertaPorId");

                    b.Property<DateTime?>("CerradaEn")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("cerradaEn");

                    b.Property<string>("CerradaPorId")
                        .HasColumnType("text")
                        .HasColumnName("cerradaPorId");

                    b.Property<string>("ComplejoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<EstadoCaja>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.\"EstadoCaja\"")
                        .HasDefaultValue(EstadoCaja.ABIERTA)
                        .HasColumnName("estado");

                    b.Property<decimal?>("MontoFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("montoFinal");

                    b.Property<decimal>("MontoInicial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("montoInicial");

                    b.HasKey("Id");

                    b.HasIndex("ComplejoId", "Estado");

                    b.ToTable("CajaSesion", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Cancha", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("ComplejoId")
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Imagen")
                        .HasColumnType("text")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioPorHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precioPorHora");

                    b.Property<string>("Superficie")
                        .HasColumnType("text")
                        .HasColumnName("superficie");

                    b.Property<bool>("Techada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("techada");

                    b.Property<TipoCancha>("Tipo")
                        .HasColumnType("public.\"TipoCancha\"")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.HasIndex("ComplejoId");

                    b.HasIndex("Tipo");

                    b.ToTable("Cancha", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Complejo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("actualizadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distrito");

                    b.Property<string>("DuenoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duenoId");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<bool>("Publicado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("publicado");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("DuenoId");

                    b.HasIndex("Publicado");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Complejo", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.ComplejoMiembro", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ComplejoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Rol>("RolSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.\"Rol\"")
                        .HasDefaultValue(Rol.PERSONAL)
                        .HasColumnName("rolSede");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ComplejoId");

                    b.HasIndex("UsuarioId", "ComplejoId")
                        .IsUnique();

                    b.ToTable("ComplejoMiembro", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.InscripcionTorneo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CapitanId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capitanId");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Equipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipo");

                    b.Property<bool>("Pagado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pagado");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("TorneoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("torneoId");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.HasIndex("TorneoId", "Equipo")
                        .IsUnique();

                    b.ToTable("InscripcionTorneo", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Meta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("Actual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("actual");

                    b.Property<string>("ComplejoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<decimal>("Objetivo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("objetivo");

                    b.Property<DateTime>("PeriodoFin")
                        .HasColumnType("date")
                        .HasColumnName("periodoFin");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("date")
                        .HasColumnName("periodoInicio");

                    b.Property<TipoMeta>("Tipo")
                        .HasColumnType("public.\"TipoMeta\"")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("ComplejoId");

                    b.ToTable("Meta", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.MovimientoCaja", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CajaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cajaId");

                    b.Property<string>("ComplejoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreadoPorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creadoPorId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<MetodoPago>("MetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.\"MetodoPago\"")
                        .HasDefaultValue(MetodoPago.EFECTIVO)
                        .HasColumnName("metodoPago");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("ProductoId")
                        .HasColumnType("text")
                        .HasColumnName("productoId");

                    b.Property<string>("ReservaId")
                        .HasColumnType("text")
                        .HasColumnName("reservaId");

                    b.Property<TipoMovimiento>("Tipo")
                        .HasColumnType("public.\"TipoMovimiento\"")
                        .HasColumnName("tipo");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ComplejoId", "CreadoEn");

                    b.ToTable("MovimientoCaja", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.PartidoTorneo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CanchaId")
                        .HasColumnType("text")
                        .HasColumnName("canchaId");

                    b.Property<string>("EquipoA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipoA");

                    b.Property<string>("EquipoB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipoB");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fase");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Ganador")
                        .HasColumnType("text")
                        .HasColumnName("ganador");

                    b.Property<int?>("GolesA")
                        .HasColumnType("integer")
                        .HasColumnName("golesA");

                    b.Property<int?>("GolesB")
                        .HasColumnType("integer")
                        .HasColumnName("golesB");

                    b.Property<string>("TorneoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("torneoId");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId", "Fase");

                    b.ToTable("PartidoTorneo", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Producto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("ComplejoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("ComplejoId", "Activo");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Promocion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("CanchaId")
                        .HasColumnType("text")
                        .HasColumnName("canchaId");

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("ComplejoId")
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("HoraDesde")
                        .HasColumnType("integer")
                        .HasColumnName("horaDesde");

                    b.Property<int?>("HoraHasta")
                        .HasColumnType("integer")
                        .HasColumnName("horaHasta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<TipoDescuento>("Tipo")
                        .HasColumnType("public.\"TipoDescuento\"")
                        .HasColumnName("tipo");

                    b.Property<int>("UsosActuales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usosActuales");

                    b.Property<int?>("UsosMax")
                        .HasColumnType("integer")
                        .HasColumnName("usosMax");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ComplejoId", "Activa");

                    b.ToTable("Promocion", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Resena", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<string>("ComplejoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer")
                        .HasColumnName("puntuacion");

                    b.Property<string>("RespuestaDueno")
                        .HasColumnType("text")
                        .HasColumnName("respuestaDueno");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ComplejoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ComplejoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("Resena", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Reserva", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CanchaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canchaId");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("ComplejoId")
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<EstadoReserva>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.\"EstadoReserva\"")
                        .HasDefaultValue(EstadoReserva.PENDIENTE)
                        .HasColumnName("estado");

                    b.Property<EstadoPago>("EstadoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.\"EstadoPago\"")
                        .HasDefaultValue(EstadoPago.PENDIENTE)
                        .HasColumnName("estadoPago");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("HoraFin")
                        .HasColumnType("integer")
                        .HasColumnName("horaFin");

                    b.Property<int>("HoraInicio")
                        .HasColumnType("integer")
                        .HasColumnName("horaInicio");

                    b.Property<MetodoPago?>("MetodoPago")
                        .HasColumnType("public.\"MetodoPago\"")
                        .HasColumnName("metodoPago");

                    b.Property<decimal>("MontoPagado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("montoPagado");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("PromocionId")
                        .HasColumnType("text")
                        .HasColumnName("promocionId");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuarioId");

                    b.Property<DateTime?>("ValidadaEn")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("validadaEn");

                    b.Property<string>("ValidadaPorId")
                        .HasColumnType("text")
                        .HasColumnName("validadaPorId");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("CanchaId", "Fecha");

                    b.HasIndex("ComplejoId", "Fecha");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Torneo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ComplejoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complejoId");

                    b.Property<decimal>("CostoInscripcion")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costoInscripcion");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CupoMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(16)
                        .HasColumnName("cupoMax");

                    b.Property<TipoCancha>("Deporte")
                        .HasColumnType("public.\"TipoCancha\"")
                        .HasColumnName("deporte");

                    b.Property<EstadoTorneo>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.\"EstadoTorneo\"")
                        .HasDefaultValue(EstadoTorneo.BORRADOR)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fechaInicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Premio")
                        .HasColumnType("text")
                        .HasColumnName("premio");

                    b.Property<string>("Reglamento")
                        .HasColumnType("text")
                        .HasColumnName("reglamento");

                    b.HasKey("Id");

                    b.HasIndex("ComplejoId", "Estado");

                    b.ToTable("Torneo", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) without time zone")
                        .HasColumnName("creadoEn")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<Rol>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.\"Rol\"")
                        .HasDefaultValue(Rol.USUARIO)
                        .HasColumnName("rol");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tokenVersion");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Rol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.CajaSesion", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Cajas")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Cancha", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Canchas")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Complejo", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Usuario", "Dueno")
                        .WithMany("ComplejosPropios")
                        .HasForeignKey("DuenoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dueno");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.ComplejoMiembro", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Miembros")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservaFacil.Api.Models.Usuario", "Usuario")
                        .WithMany("Membresias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.InscripcionTorneo", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Torneo", "Torneo")
                        .WithMany("Inscripciones")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Meta", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Metas")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.MovimientoCaja", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.CajaSesion", "Caja")
                        .WithMany("Movimientos")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReservaFacil.Api.Models.Complejo", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservaFacil.Api.Models.Usuario", null)
                        .WithMany("MovimientosCreados")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Caja");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.PartidoTorneo", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Torneo", "Torneo")
                        .WithMany("Partidos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Producto", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Productos")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Promocion", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Promociones")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Resena", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Resenas")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservaFacil.Api.Models.Usuario", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Reserva", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Reservas")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReservaFacil.Api.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Complejo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Torneo", b =>
                {
                    b.HasOne("ReservaFacil.Api.Models.Complejo", "Complejo")
                        .WithMany("Torneos")
                        .HasForeignKey("ComplejoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.CajaSesion", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Cancha", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Complejo", b =>
                {
                    b.Navigation("Cajas");

                    b.Navigation("Canchas");

                    b.Navigation("Metas");

                    b.Navigation("Miembros");

                    b.Navigation("Movimientos");

                    b.Navigation("Productos");

                    b.Navigation("Promociones");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");

                    b.Navigation("Torneos");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Torneo", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("ReservaFacil.Api.Models.Usuario", b =>
                {
                    b.Navigation("ComplejosPropios");

                    b.Navigation("Membresias");

                    b.Navigation("MovimientosCreados");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
