backend:
  name: github
  repo: ImLukzy/educlook-web
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Autor", name: "author", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", required: false, default: false }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descripcion", name: "description", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
  - name: "a_quien_ayudo"
    label: "A quien ayudo"
    folder: "src/pages/a-quien-ayudo"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ContentLayout.astro" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descripcion", name: "description", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
  - name: "comparar"
    label: "Comparar"
    folder: "src/pages/comparar"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ContentLayout.astro" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descripcion", name: "description", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
  - name: "recursos"
    label: "Recursos"
    folder: "src/pages/recursos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ContentLayout.astro" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descripcion", name: "description", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
  - name: "empresa"
    label: "Empresa"
    folder: "src/pages/empresa"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/ContentLayout.astro" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descripcion", name: "description", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
