// Preguntas del jugador (copy verificado contra el código en la spec 45).
// Única fuente: portada y /ayuda (spec 47).
export const PREGUNTAS_JUGADOR = [
  { categoria: "Cuenta", icono: "usuario", pregunta: "¿Necesito cuenta?", respuesta: "Sí, necesitas una cuenta para enviar una reserva y revisar su estado. Primero buscas por distrito, deporte y día; después eliges una cancha disponible e inicias sesión para continuar. Cuando el complejo confirma, encuentras el código de la reserva en Mi partido. La herramienta para sortear equipos sí se puede usar sin cuenta." },
  { categoria: "Reservas", icono: "calendario", pregunta: "¿Puedo reservar para otro día?", respuesta: "Puedes buscar una cancha para hoy o para mañana. En el buscador seleccionas el distrito, el deporte y uno de esos dos días; en los resultados eliges la hora disponible que te convenga. Después envías la solicitud de reserva y el complejo decide si la confirma. La disponibilidad depende de los horarios publicados por cada complejo." },
  { categoria: "Código", icono: "ticket", pregunta: "¿Qué es el código de reserva?", respuesta: "Es el código que identifica una reserva confirmada. Envías la solicitud, esperas la confirmación del complejo y luego abres Mi partido para verlo. Al llegar, muestras ese código en la cancha como referencia de tu reserva. Mientras la solicitud siga pendiente, todavía no aparece un código confirmado." },
  { categoria: "Reservas", icono: "reloj", pregunta: "¿Qué pasa si mi reserva queda pendiente?", respuesta: "Significa que el complejo todavía debe aceptar o rechazar tu solicitud. Después de elegir la cancha y enviar la reserva, puedes revisar su estado en Mi partido. Si el complejo la confirma, allí verás el código que presentarás al llegar. La decisión y el momento de la confirmación dependen del complejo." },
  { categoria: "Pagos", icono: "billete", pregunta: "¿Necesito pagar en la página?", respuesta: "No, ReservaYa no te pide pagar la reserva en esta página. Primero buscas una hora, envías la solicitud y esperas que el complejo la confirme. El pago se coordina directamente con el complejo, porque cada uno define cómo cobra. Revisa los datos de tu reserva y consulta al complejo si necesitas conocer sus condiciones." },
  { categoria: "Distritos", icono: "lugar", pregunta: "¿En qué distritos hay canchas?", respuesta: "El buscador incluye los 29 distritos de Arequipa. Abre el campo Distrito, elige uno y combina ese filtro con el deporte y el día que buscas. Después verás las canchas que coinciden con tu selección y sus horas disponibles. La lista puede variar según los complejos que estén publicados." },
  { categoria: "Búsqueda", icono: "buscar", pregunta: "¿Cómo encuentro una cancha libre?", respuesta: "Usa el buscador de la portada para filtrar las opciones disponibles. Elige distrito, deporte y día, pulsa Buscar canchas y revisa los resultados con sus horas y precios publicados. Desde una opción disponible puedes continuar con la solicitud de reserva. El resultado depende de la información y los horarios que haya cargado cada complejo." },
  { categoria: "Partidos", icono: "grupo", pregunta: "¿Qué hago si me faltan jugadores?", respuesta: "Puedes revisar los partidos abiertos o publicar el tuyo para buscar jugadores. Entra a la sección de partidos, mira las convocatorias disponibles y abre la que te interese; si ninguna encaja, crea una con los datos de tu partido. Después otros jugadores pueden encontrar esa publicación. La organización final la coordinan quienes participan." },
] as const;
